# Generated by Django 6.0 on 2025-12-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_add_slug_to_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="zipcode",
            new_name="zip",
        ),
    ]
