# Generated by Django 6.0 on 2025-12-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_rename_zipcode_address_zip"),
    ]

    operations = [
        migrations.RunSQL(
                        """
            INSERT INTO store_collection (title) 
            VALUES ('collection1')
            """, 
            """
            DELETE FROM store_collection
            WHERE title = 'collection1'
            """
                        )
    ]
