# Generated by Django 6.0 on 2026-01-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_auto_20251230_2025"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="store_custo_last_na_e6a359_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="customer",
            table="store_customers",
        ),
    ]
